name: Actions Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List resources
        run: |
          pwd
          ls
