name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display a String
        run: echo "Hello World"
      - name: Multilines Script
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Location Window
        run: Get-Location
      - name: Directory Location Bash
        run: pwd
        shell: bash
